[package]
name = "l75"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "merge_alt"
path = "src/merge_alt.rs"

[[bin]]
name = "greates_div"
path = "src/greates_div.rs"

[[bin]]
name = "kids_candies"
path = "src/kids_candies.rs"

[[bin]]
name = "place_flowers"
path = "src/place_flowers.rs"

[[bin]]
name = "reverse_vowels"
path = "src/reverse_vowels.rs"

[dependencies]
